### ISSUE TITLE
White Screen/Can't connect to server when attempting to create room

### ISSUE THREAD

**Issue by Tonebone58** [benank/everyone.dance#30]
Downloaded it and got it installed with my Simply Love but it either would tell me I can't connect and/or just give me a white screen and freeze (90% of the time), partner I planned to play with also had the same issue.

**Comment by benank** [comment]
Thanks for the report! Not quite sure what is happening here, but I'll need just a bit of information to help me debug it:

Could you please let me know: 
- Your operating system (windows, linux, mac)
- StepMania version
- Simply Love version
- everyone.dance version (assumed 2.3.0 - you can check the version in the installation menu)

White screen and freezing usually means that the user interface broke, and there's an error somewhere! I've been able to replicate your issue and have pushed a fix for it in version 2.3.2. The issue seems to stem from everyone.dance not recognizing the installation properly. Please try the new version and let me know if it works!

And just to be clear - the installation worked fine when you installed it through the Installation menu? Your Simply Love theme should have a check next to it if it worked.
